version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app  # Mount the entire backend directory
      - ./backend/audio:/app/audio
      - ./backend/uploads:/app/uploads
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html  # Mount the frontend directory
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
